dependencies:
  dhtxx:
    url: github.com/toitware/toit-dhtxx
    version: ^1.10.0
  hc-sr04:
    url: github.com/lask/toit-hc-sr04
    version: ^2.2.0
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.13.1
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.1.0
